# few shot exp 6
# input: subtracted volume, code get regression model, as input (add_size=1), normalization term is taking log of time then divide by constant 3
# adapt_lin: false
add_size: 1
regress_tdi: true
# add_size: 1 

# baseline: true
device: 0
gamma: 0.95
hidden: 1024
iteration: 1001
label_ext: pt
label_log: false
label_root: cura_output/print_time
loss_func: huber_loss
lr: 0.0003
lr_ratio: 0.1
lr_step: 100
partial: lora

rank: 4
pre_path: pretrain_experiment/exp22/153400_iter.pt
pretrain: volume
# range_log: false
range_log: false
range_root: inputs/range1_cura
# range_root: nx-cam-output-v2/log_min_time
regress_norm: true
# means if i multiply at the end

#if true, will run linear regression on task-dependent input
save_dir: scratch_experiment
seed: 1
shots: 100
splits: inputs/data/cura_train_val_test.json
test_batch: 64
train_batch: 128
val_every: 100
