
add_size: 0
regress_tdi: false

device: 0
gamma: 0.95
hidden: 1024
iteration: 1001
label_ext: pt
label_log: false
label_root: recoat/interfere
loss_func: huber_loss
lr: 0.0003
lr_ratio: 1
lr_step: 100

pre_path: virl-pretrained.pt
pretrain: volume
# range_log: false
range_log: false
range_root: v_sub
# range_root: nx-cam-output-v2/log_min_time
regress_norm: false
# means if i multiply at the end

#if true, will run linear regression on task-dependent input
save_dir: scratch_experiment
seed: 1
shots: 100
splits: inputs/data/recoat_train_val_test.json
test_batch: 64
train_batch: 128
val_every: 100

#### training strategy

## if train from scratch, uncomment nothing (partial: None)

## if linear probe, uncomment the following # because encoder is frozen, lr_ratio does not matter
partial: lin

## if finetuning, uncomment the following
# partial: finetune
# lr_ratio: 0.1

## if using lora, uncomment the following
# partial: lora
# rank: 4
